### ISSUE TITLE
Try cosine similarity instead of the basic boolean model

### ISSUE THREAD

**Issue by CraigBryan** [CraigBryan/csi4107-tweet-search#2]

**Comment by CraigBryan** [comment]
So, reading the Lucene docs, it seems the TFIDFSimilarity uses both the boolean model and the cosine similarity. It uses the boolean model to decide whether or not to score at all. If the boolean model says "yes", it then scores the document with cosine similarity.

**Comment by BonShillings** [comment]
I added a class that can compute Cosine Similarity for two documents/queries but I'm not sure if we want to use it or just go with the Default Similarity.

**Comment by BonShillings** [comment]
TFIDF for the win
