### ISSUE TITLE
Interpreting Hashtags

### ISSUE THREAD

**Issue by BonShillings** [CraigBryan/csi4107-tweet-search#4]
We should probably create a Tokenizer/Analyzer that interprets hashtags specifically and adds weighting to those terms.

We could find a way to add weights to these terms while we index the documents (Extend the Analyzer/Tokenizer)
or
We can inject this function into our Similarity Computation somehow (we would have to implement our own Similarity Class)

**Comment by CraigBryan** [comment]
An interesting step would be to see what lucene does now with hashtags. I assume it just takes the '#' off the end and parses the word normally.

**Comment by BonShillings** [comment]
Hey, so i've been putting in some work this evening and I found that extending the analyzer/tokenizer is a crazy task. What I did instead for hashtags was to create a separate createHashtagIndex() method and parse the tweet for words that start with a hashtag and then and use a whitespace analyzer to create an index with hashtag terms. 

What are your thought on a system that would supplement the existing scoring with this hashtag index?

**Comment by BonShillings** [comment]
I'm going to first try to implement a scoring that minimizes rank over both fields.

**Comment by CraigBryan** [comment]
Hmm. I think it'd be really cool, does it remove the hashtag words from the
normal index?

Also, I don't think I have time to work on it, but I'm happy to let you
work on it as I tidy up the code, comment, and write a bunch of the report.
Does that sound amenable?

**Comment by BonShillings** [comment]
The hashtag words are still in the normal index as well at this point. 

Ya this works fine, could you also test the implementation after I commit it though, just toggle the functionality on off and compare the results? I still can't run trec_eval, not even a fresh download from the command line. 

I should be able to push the changes tonight, or tomorrow morning.

**Comment by CraigBryan** [comment]
Haha, I can do that. I've got command line arguments for everything else
now.

**Comment by BonShillings** [comment]
I just committed the hashtag indexing methods (in Query Processor) They seam to be working and generating new information/scoring, but I'm not sure of the quality of the results

**Comment by CraigBryan** [comment]
Hey, question about part of your code. 

Why are you inverting your comparison here?:

```
@Override
public int compare(final IDandScore a, final IDandScore b) {

    return (-1) * a.score.compareTo(b.score);
}
```

Its in getResults of the QueryProcessor.

**Comment by BonShillings** [comment]
The regular float comparator returns 1 if float a is less than float b, in other words it would try to sort the floats in ascending order (lowest first, highest last), by reversing this comparator we end up sorting for the opposite order (highest first, lowest last)

**Comment by CraigBryan** [comment]
Ok great, makes sense. I've reimplemented that a nicer way, and I'll make sure it's reversed.
