### ISSUE TITLE
Try different analyzers

### ISSUE THREAD

**Issue by CraigBryan** [CraigBryan/csi4107-tweet-search#5]
I just added an option to use Lucene's EnglishAnalyzer (EA) instead of the StandardAnalyzer (SA). They both do tokenizing and stemming (with the same word bank, I think), but the EA also does stemming (using porter stemmer)  and possessive filtering (gets rid of 's). Interestingly, the EA get a better average precision, but a worse P@10 than the SA.

**Comment by CraigBryan** [comment]
Although, upon further investigation, it appears there are no more useful built-in analyzers, unless a lot of the tweets are in a particular language.

**Comment by BonShillings** [comment]
Hey, I couldn't find this in the last commit, but I added the hashtag functionality to the master branch. The functionality should work with other analyzers if you want to pull the changes to your working branch.

**Comment by CraigBryan** [comment]
Yeah, I haven't pushed it, because it would've made it difficult for you to push your changes. Expect a push tonight.
